## Obtain Python Jupyter, etc.
* www.python.org download python
* python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose

Anaconda
https://www.anaconda.com/distribution/

Enthought Canopy
https://www.enthought.com/product/canopy/

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def f(x,y):
    return np.array([x**2-2*x-y+1,x**2+y**2-1])
def df(x,y):
    return np.array([[2*x-2,-1],[2*x,2*y]])

In [36]:
x0 = [-0.1,-2]
xn = x0

In [51]:
p = np.linalg.solve(df(xn[0],xn[1]),f(xn[0],xn[1]))
p

array([ 3.65335539e-10, -6.28972651e-10])

In [52]:
xn = xn - p
xn

array([1.00000000e+00, 3.34314187e-17])

In [60]:
x0 = [-0.1,1]
xn = x0

In [61]:
p = np.linalg.solve(df(xn[0],xn[1]),f(xn[0],xn[1]))
while (np.linalg.norm(p)>1e-10):
    xn = xn - p
    p = np.linalg.solve(df(xn[0],xn[1]),f(xn[0],xn[1]))

In [62]:
xn

array([1.91513043e-17, 1.00000000e+00])

In [66]:
A = np.random.randn(100,100)
b = np.random.rand(100)

In [67]:
%%timeit
Ainv = np.linalg.inv(A)
x = Ainv*b

The slowest run took 8.43 times longer than the fastest. This could mean that an intermediate result is being cached.
1.72 ms ± 1.63 ms per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [68]:
%%timeit
x = np.linalg.solve(A,b)

304 µs ± 819 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
